src/ext/components/partial-dependence-input.coffee
src/ext/components/partial-dependence-input.jade
src/ext/modules/proxy.coffee
src/ext/modules/routines.coffee

This PR adds comments to code for the partial dependence plot to help developers new to Flow understand what is happening, where.

add comments for partial dependence plot implementation

---

README.md

based on a conversation with @lo5

clarify how to develop flow without re-building h2o

---

README.md

documenting the required h2o-3 setup step in the flow developer docs. thanks to @lo5 for pointing me to this setup step 😄

add link to `./gradlew idea` instructions

---

README.md

...to see changes to Flow rendered in the browser

clarify that dev needs to run `make`

---

src/ext/components/partial-dependence-input.coffee
src/ext/components/partial-dependence-input.jade
src/ext/components/partial-dependence-output.coffee
src/ext/components/partial-dependence-output.jade

- Added a checkbox on input form to trigger the mode for selecting columns
- The column selector is only shown when "Select columns?" is selected
- Replicates most of the model builder param list for search and pagination
- Added exceptions box 
- Added a checkbox on output form for data table visibility. Changed default display behavior to uncollapsed, with to data tables. 
Thanks @lo5 for all the help! :D

PDP with Column Selector

---

src/core/flow.coffee

This will make `x-h2o-context-path` header check case insensitive and resolve [PUBDEV-3903](https://0xdata.atlassian.net/browse/PUBDEV-3903)

[PUBDEV-3903] `x-h2o-context-path` check

---

README.md

This PR adds an extended description of the technology and design philosophy behind Flow

add-flow-extended-decription

---

src/ext/components/model-output.coffee
src/ext/components/model-output.jade

Added Gen jar download button for one click download rather than using the curl command.

Added Gen jar download button

---

src/core/components/notebook.coffee
src/ext/components/h2o.jade
src/ext/modules/routines.coffee

This should not be directly merged!

Remove user-facing mentions of AutoML 

---

src/ext/components/automodel-input.coffee
src/ext/components/automodel-input.jade
src/ext/components/model-input.coffee
src/ext/modules/routines.coffee
src/ext/modules/util.coffee

I have to move a few methods to the H2O.Util so we can access them from multiple coffee scripts. Please tell me if there is a nicer way to do this.

[PUBDEV-4719] Added the ignored_columns to AutoML

---

src/ext/components/model-output.coffee

Added formatting support for new H2O type

PUBDEV-5204: Allow user to specify explicit list of interactions in GLM

---

src/ext/components/model-input.coffee

[PUBDEV-5102] Populate metalearner_fold_column list

---

src/ext/components/automodel-input.coffee
src/ext/components/automodel-input.jade
src/ext/modules/routines.coffee

[PUBDEV-5274] Add exclude_algos to AutoML

---

src/ext/components/h2o.jade
src/ext/components/model-input.coffee
src/ext/components/model-parameter-stringpairs.jade
src/ext/modules/proxy.coffee

Adds component which is used to specify list of pairwise interactions.

[PUBDEV-5408] interaction_pairs component

---

jenkins/Jenkinsfile-release

- rel-... branch is always compatible with rel-... of h2o-3
- release 0.7.XX from rel-wright only

[ITA-328] Modify release process.

---

.gitignore
h2o-flow.iml
src/ext/components/automodel-input.coffee
src/ext/components/automodel-input.jade
src/ext/modules/routines.coffee

This reverts commit d8b8c99854f124b351d9a59a6dc92828238ed5cf, reversing
changes made to ee725bd5189d4579dd4d0b062335b50d51993a66.

Revert "Merge pull request #78 from h2oai/PUBDEV-5668"

---

src/core/components/notebook.coffee

Adds `Download Gen Model` button to Admin Menu, under Advanced section.

[PUBDEV-5822] Add Download Gen Model button to Admin Menu.

---

src/core/modules/util.coffee
src/ext/components/predict-output.coffee

When making predictions using regression model, there is no CM which
cause issues in PhantomJS (probably older browsers as well).
(cherry picked from commit bbce9fb0e8d161c467e2b1546c1cf3e4ed22f7a5)

[PUBDEV-5748] Fix issue for models without CM.

---

src/core/modules/util.coffee

https://0xdata.atlassian.net/browse/PUBDEV-6050

[PUBDEV-6050] Fix swapped precision and recall values.

---

docker/Dockerfile

Updates to node 10.
Adds g++ and bzip2.

Node 10, add g++ and bzip2.

---

src/core/components/notebook.coffee
src/ext/components/model-output.coffee

- making them work also when custom context prefix is present

[PUBDEV-6109] add ContextPath to all window.open calls

---

docker/Dockerfile
docker/scripts/warmup_caches
package-lock.json

Downgrade event-stream to 3.3.5.
Update har-validator to 5.1.3.

[BUILD] Fix dependencies.

---

build/js/headless-test.js
test/headless-test.coffee

In docker there are some issues (related to old kernel to test machines), we need to use --no-sandbox.

Fix tests.

---

src/ext/components/split-frame-input.coffee
src/ext/modules/routines.coffee

`sort` and `unique` functions were undefined.
https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6192

[PUBDEV-6192] Fix frame splitting.

---

src/ext/components/import-sql-table-input.coffee

[PUBDEV-6201] Fix SQL import.

---

package-lock.json
package.json

[PUBDEV-6204] Fix interaction pairs.

---

package-lock.json
package.json

https://github.com/ahmadnassri/node-har-validator/issues/113

[BUILD] Freeze har-validator version on 5.1.3.

---

src/ext/components/import-files-input.coffee

JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6300
H2O-3 PR: https://github.com/h2oai/h2o-3/pull/3326
Original status:

PUBDEV-6300 - Flows throws error on an empty path while performing 'Import Files' operation

---

src/core/components/cell.coffee
src/core/modules/coffeescript-kernel.coffee
src/core/modules/gui.coffee
src/core/modules/prelude.coffee
src/ext/components/model-output.coffee
src/ext/modules/proxy.coffee
src/ext/modules/routines.coffee

- fixes bug introduced with parsing large numbers as BigNumber (jsonBig) because of Long seed values

[PUBDEV-6451] fix isNumber/isObject for BigNumber instances

---

src/ext/components/cloud-output.coffee
src/ext/modules/application-context.coffee

- remove displaying of values no longer supplied by the back end

[PUBDEV-6533] fix NaNs in Cluster status screen

---

src/ext/components/automodel-input.coffee
src/ext/components/automodel-input.pug
src/ext/modules/routines.coffee

https://0xdata.atlassian.net/browse/PUBDEV-6601
adding support for `blending_frame` and `max_runtime_per_model` in Flow

PUBDEV-6601: adding missing AutoML properties in Flow to reflect latest changes

---

src/ext/components/model-input.coffee

https://0xdata.atlassian.net/browse/PUBDEV-6837
Let it flow, let it flow, let it flow.
[![](http://img.youtube.com/vi/l_pCeT9AyUY/0.jpg)](http://www.youtube.com/watch?v=l_pCeT9AyUY "")

PUBDEV-6837 - TargetEncoder support.

---

src/ext/components/model-input.coffee

JIRA: https://0xdata.atlassian.net/browse/PUBDEV-6967'
H2O part: https://github.com/h2oai/h2o-3/pull/3971
As TE acts as a full-fledged model, these code changes done in Flow are no longer needed. This PR only reverts previous commit done by me.
YouTube video demonstration:
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/LXNk92e3tRI/0.jpg)](https://www.youtube.com/watch?v=LXNk92e3tRI)

PUBDEV-6967 - Revert target-encoder specific changes to flow. No longer needed.

---

jenkins/Jenkinsfile-release

changing the node to fix release build

Seb jenkins node

---

jenkins/Jenkinsfile-release

fix jenkins release pipeline (attempt 3)

---

jenkins/Jenkinsfile-release

fix jenkins release script

---

src/ext/components/partial-dependence-input.coffee
src/ext/components/partial-dependence-input.pug
src/ext/components/partial-dependence-output.coffee

Allow plot multinomial PDP via `target` parameter. 
It is just the first version, which allows plot multinomial PDP only for one target class. 
Next step is to allow plot multinomial PDP for more than one target class and add possibility to select available target classes to user. 
JIRA: https://0xdata.atlassian.net/projects/PUBDEV/issues/PUBDEV-6250

PUBDEV-6250 allow PDP for multinomial model

---

src/ext/components/parse-input.coffee

By parsing https://s3.amazonaws.com/h2o-public-test-data/smalldata/junit/cars_20mpg.csv I was able to get `charCodeAt(0) is not a function` exception. 0 is a default value, so it's not needed as an argument and this PR fixes it.

PUBDEV-8087: fix

---

src/ext/components/automl-input.coffee

https://h2oai.atlassian.net/browse/PUBDEV-7858

PUBDEV-7858: Expose distribution parameter in AutoML

---

src/ext/components/job-output.coffee

https://h2oai.atlassian.net/browse/PUBDEV-8736
This was broken since https://github.com/h2oai/h2o-flow/commit/b1003755fd917d8f54fa35afc37b9a9dfbc785d9 .

PUBDEV-8736: After an AutoML job the View button does not work

---

.github/workflows/snyk-scan.yml

- Added the repo to a new organisation in [Snyk (H2O-3)](https://app.snyk.io/org/h2o-3)
- Triggered using - [H2O_3_SNYK_TOKEN](https://app.snyk.io/org/h2o-3/manage/service-accounts)
**PARENT_ISSUES**
- https://github.com/h2oai/h2o-ops/issues/278
- https://github.com/h2oai/h2o-ops/issues/241

[DevOps] Snyk Integration

---

CHANGELOG.md
src/core/components/notebook.coffee

Closes https://github.com/h2oai/h2o-3/issues/15626

[GH-15626] Replace JIRA links in H2O Flow UI to GH issues
